cl scr
SET PAGESIZE 50;
SET LINESIZE 200;
DROP TABLE RESERVATION;

DROP TABLE SAILOR;
DROP TABLE BOAT;

CREATE TABLE SAILOR (
  SID varchar2(4) PRIMARY KEY ,
  SNAME varchar2(15) NOT NULL ,
  MNAME varchar2(15) ,
  SURNAME varchar2(15) NOT NULL,
  RATING number(2) DEFAULT 0,
  AGE number(3,1) NOT NULL,
  CONSTRAINT SID_starts CHECK (sid LIKE 's%'),
  CONSTRAINT SNAME_cap CHECK (sname = INITCAP(sname))
);
CREATE TABLE BOAT(
    BID number(3) PRIMARY KEY,
    BNAME varchar2(10),
    COLOR varchar2(6),
    -- CONSTRAINT BID_starts CHECK (bid LIKE 'b%'),
    CONSTRAINT BNAME_upper CHECK (BNAME = UPPER(BNAME)),
    CONSTRAINT COLOR_code CHECK (COLOR in ('RED','GREEN','BLUE'))
);
CREATE TABLE RESERVATION(
    SID varchar2(4) NOT NULL,
    BID number(3) NOT NULL,
    DAY date NOT NULL,
    CONSTRAINT pk_reser PRIMARY KEY(SID,BID),
    FOREIGN KEY (sid) REFERENCES SAILOR (sid),
    FOREIGN KEY (bid) REFERENCES BOAT (bid),
    CONSTRAINT day_check CHECK(DAY<TO_DATE('01-JAN-2000','DD-Mon-YYYY'))
);
SELECT TABLE_NAME, CONSTRAINT_NAME, R_CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('SAILOR', 'BOAT','RESERVATION');

@data4.sql  